#!/usr/bin/env node

// cc-ghost-log cron setup
// Adds a daily 8:00 AM job that runs when yesterday was a Ghost Day.
// Writes summary + tweet text to ~/ops/ghost-reports/YYYY-MM-DD.md

import { execSync, spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const REPORT_DIR = join(homedir(), 'ops', 'ghost-reports');
const SCRIPT_PATH = join(homedir(), 'bin', 'ghost-daily-report.sh');

// ── Create report directory ───────────────────────────────────────────────────
if (!existsSync(REPORT_DIR)) {
  mkdirSync(REPORT_DIR, { recursive: true });
  console.log(`Created: ${REPORT_DIR}`);
}

// ── Create the daily script ───────────────────────────────────────────────────
const dailyScript = `#!/bin/bash
# ghost-daily-report.sh — auto-generated by cc-ghost-log setup-cron
# Runs every morning. If yesterday was a Ghost Day, writes a report.

set -e
REPORT_DIR="$HOME/ops/ghost-reports"
DATE=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d)
REPORT_FILE="$REPORT_DIR/$DATE.md"

# Skip if already written
[ -f "$REPORT_FILE" ] && exit 0

# Check if yesterday was a Ghost Day (exit 0 = yes)
npx cc-ghost-log --check-yesterday || exit 0

# It was a Ghost Day — generate report
mkdir -p "$REPORT_DIR"
{
  npx cc-ghost-log --yesterday --summary
  echo ""
  echo "---"
  echo ""
  echo "**Tweet:**"
  echo ""
  npx cc-ghost-log --yesterday --tweet
} > "$REPORT_FILE"

echo "Ghost Day report written: $REPORT_FILE"
`;

if (!existsSync(join(homedir(), 'bin'))) {
  mkdirSync(join(homedir(), 'bin'), { recursive: true });
}
writeFileSync(SCRIPT_PATH, dailyScript, { mode: 0o755 });
console.log(`Created: ${SCRIPT_PATH}`);

// ── Add cron entry ────────────────────────────────────────────────────────────
const CRON_TAG = '# cc-ghost-log-daily';
let current = '';
try {
  current = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' });
} catch {}

if (current.includes(CRON_TAG)) {
  console.log('Cron entry already exists. Skipping.');
} else {
  const newCron = current.trim() + `\n0 8 * * * ${SCRIPT_PATH} >> ${REPORT_DIR}/cron.log 2>&1 ${CRON_TAG}\n`;
  const tmp = `/tmp/crontab-${Date.now()}.txt`;
  writeFileSync(tmp, newCron);
  spawnSync('crontab', [tmp], { stdio: 'inherit' });
  console.log('Cron entry added: runs daily at 8:00 AM');
}

console.log('\nSetup complete.');
console.log(`Reports will be saved to: ${REPORT_DIR}/YYYY-MM-DD.md`);
console.log('\nManual test:');
console.log(`  npx cc-ghost-log --yesterday --summary`);
console.log(`  npx cc-ghost-log --yesterday --tweet`);
